In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

crime = pd.read_csv("Crime_Data_from_2020_to_Present.csv")

## Data Exploration

In [2]:
crime.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,190326475,3/1/2020 0:00,3/1/2020 0:00,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
1,200106753,2/9/2020 0:00,2/8/2020 0:00,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 0:00,11/4/2020 0:00,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
3,200907217,5/10/2023 0:00,3/10/2020 0:00,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,IC,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
4,200412582,9/9/2020 0:00,9/9/2020 0:00,630,4,Hollenbeck,413,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,200 E AVENUE 28,NaN,34.0820,-118.2130

In [3]:
crime.shape

(1005198, 28)

In [4]:
crime.columns

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes',
       'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc',
       'Weapon Used Cd', 'Weapon Desc', 'Status', 'Status Desc', 'Crm Cd 1',
       'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'Cross Street', 'LAT',
       'LON'],
      dtype='str')

In [5]:
crime.info()

<class 'pandas.DataFrame'>
RangeIndex: 1005198 entries, 0 to 1005197
Data columns (total 28 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   DR_NO           1005198 non-null  int64
 1   Date Rptd       1005198 non-null  str
 2   DATE OCC        1005198 non-null  str
 3   TIME OCC        1005198 non-null  int64
 4   AREA            1005198 non-null  int64
 5   AREA NAME       1005198 non-null  str
 6   Rpt Dist No     1005198 non-null  int64
 7   Part 1-2        1005198 non-null  int64
 8   Crm Cd          1005198 non-null  int64
 9   Crm Cd Desc     1005198 non-null  str
 10  Mocodes         853438 non-null   str
 11  Vict Age        1005198 non-null  int64
 12  Vict Sex        860416 non-null   str
 13  Vict Descent    860404 non-null   str
 14  Premis Cd       1005182 non-null  float64
 15  Premis Desc     1004610 non-null  str
 16  Weapon Used Cd  327280 non-null   float64
 17  Weapon Desc     327280 non-null   str
 18  Status          1005197 non-null  str
 19  Status Desc     1005198 non-null  str
 20  Crm Cd 1        1005187 non-null  float64
 21  Crm Cd 2        69159 non-null    float64
 22  Crm Cd 3        2314 non-null     float64
 23  Crm Cd 4        64 non-null       float64
 24  LOCATION        1005198 non-null  str
 25  Cross Street    154243 non-null   str
 26  LAT             1005198 non-null  float64
 27  LON             1005198 non-null  float64
dtypes: float64(8), int64(7), str(13)
memory usage: 214.7 MB

In [6]:
crime.isnull().sum()[crime.isnull().sum() > 0]

Mocodes            151760
Vict Sex           144782
Vict Descent       144794
Premis Cd              16
Premis Desc           588
Weapon Used Cd     677918
Weapon Desc        677918
Status                  1
Crm Cd 1               11
Crm Cd 2           936039
Crm Cd 3          1002884
Crm Cd 4          1005134
Cross Street       850955
dtype: int64

In [7]:
crime.nunique()

DR_NO             1005198
Date Rptd            1906
DATE OCC             1901
TIME OCC             1439
AREA                   21
AREA NAME              21
Rpt Dist No          1210
Part 1-2                2
Crm Cd                140
Crm Cd Desc           140
Mocodes            310956
Vict Age              104
Vict Sex                5
Vict Descent           20
Premis Cd             314
Premis Desc           306
Weapon Used Cd         79
Weapon Desc            79
Status                  6
Status Desc             6
Crm Cd 1              142
Crm Cd 2              126
Crm Cd 3               38
Crm Cd 4                6
LOCATION            66567
Cross Street        10414
LAT                  5426
LON                  4982
dtype: int64

In [8]:
crime.duplicated().sum()

np.int64(0)

In [9]:
pd.options.display.float_format = "{:,.2f}".format
crime.describe()

,DR_NO,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LAT,LON
count,"1,005,198.00","1,005,198.00","1,005,198.00","1,005,198.00","1,005,198.00","1,005,198.00","1,005,198.00","1,005,182.00","327,280.00","1,005,187.00","69,159.00","2,314.00",64.00,"1,005,198.00","1,005,198.00"
mean,"220,227,677.87","1,339.91",10.69,"1,115.56",1.40,500.15,28.91,305.62,363.95,499.91,958.11,984.02,991.22,34.00,-118.09
std,"13,202,822.08",651.05,6.11,611.17,0.49,205.26,21.99,219.32,123.74,205.06,110.35,52.35,27.07,1.61,5.58
min,817.00,1.00,1.00,101.00,1.00,110.00,-4.00,101.00,101.00,110.00,210.00,310.00,821.00,0.00,-118.67
25%,"210,616,927.25",900.00,5.00,587.00,1.00,331.00,0.00,101.00,311.00,331.00,998.00,998.00,998.00,34.01,-118.43
50%,"220,916,044.00","1,420.00",11.00,"1,139.00",1.00,442.00,30.00,203.00,400.00,442.00,998.00,998.00,998.00,34.06,-118.32
75%,"231,110,516.25","1,900.00",16.00,"1,613.00",2.00,626.00,44.00,501.00,400.00,626.00,998.00,998.00,998.00,34.16,-118.27
max,"252,104,146.00","2,359.00",21.00,"2,199.00",2.00,956.00,120.00,976.00,516.00,956.00,999.00,999.00,999.00,34.33,0.00

In [10]:
crime["DR_NO"].duplicated().sum()

np.int64(0)

In [11]:
crime[crime["Vict Age"] <= 0]["Vict Age"].value_counts()

Vict Age
 0    269377
-1        99
-2        28
-3         6
-4         3
Name: count, dtype: int64

In [12]:
crime[crime["Vict Age"] >= 100]["Vict Age"].value_counts()

Vict Age
120    1
Name: count, dtype: int64

In [13]:
crime[crime["LAT"] == 0]["LAT"].value_counts()

LAT
0.00    2240
Name: count, dtype: int64

In [14]:
crime[crime["LON"] == 0]["LON"].value_counts()

LON
0.00    2240
Name: count, dtype: int64

In [15]:
crime[(crime["LAT"] == 0) & (crime["LON"] == 0)].shape[0]

2240

In [16]:
crime.describe(include="str")

,Date Rptd,DATE OCC,AREA NAME,Crm Cd Desc,Mocodes,Vict Sex,Vict Descent,Premis Desc,Weapon Desc,Status,Status Desc,LOCATION,Cross Street
count,1005198,1005198,1005198,1005198,853438,860416,860404,1004610,327280,1005197,1005198,1005198,154243
unique,1906,1901,21,140,310956,5,20,306,79,6,6,66567,10414
top,2/2/2023 0:00,1/1/2020 0:00,Central,VEHICLE - STOLEN,344,M,H,STREET,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,800 N ALAMEDA ST,BROADWAY
freq,929,1164,69674,115247,42200,403916,296437,261389,174777,803946,803946,2598,2487

In [17]:
missing_values = ["-", "", "Unknown", "unknown", "UNK", "NA", "na", "N/A"]

for col in crime.columns:
    count = crime[col].isin(missing_values).sum()
    if count > 0:
        print(col, count)

Vict Sex 1
Vict Descent 2
Status Desc 7
LOCATION 1

In [18]:
crime["Vict Sex"].value_counts(dropna=False)

Vict Sex
M      403916
F      358599
NaN    144782
X       97786
H         114
-           1
Name: count, dtype: int64

In [19]:
crime[crime["Vict Sex"].isin(missing_values)]

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
807776,232012240,6/29/2023 0:00,6/29/2023 0:00,2115,20,Olympic,2091,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.00,NaN,NaN,NaN,1900 S WESTERN AV,NaN,34.04,-118.31

In [20]:
crime["Vict Descent"].value_counts(dropna=False)

Vict Descent
H      296437
W      201451
NaN    144794
B      135823
X      106699
O       78010
A       21340
K        5991
F        4838
C        4631
J        1586
V        1195
I        1015
Z         577
P         288
U         221
D          91
L          77
G          74
S          58
-           2
Name: count, dtype: int64

In [21]:
crime[crime["Vict Descent"].isin(missing_values)]

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
756229,230908075,4/12/2023 0:00,3/30/2023 0:00,1200,9,Van Nuys,952,2,649,DOCUMENT FORGERY / STOLEN FELONY,...,IC,Invest Cont,649.00,NaN,NaN,NaN,15300 MAGNOLIA BL,NaN,34.17,-118.46
807776,232012240,6/29/2023 0:00,6/29/2023 0:00,2115,20,Olympic,2091,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.00,NaN,NaN,NaN,1900 S WESTERN AV,NaN,34.04,-118.31

In [22]:
crime[crime["Status Desc"].isin(missing_values)]

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
487935,220125552,12/1/2022 0:00,11/16/2022 0:00,1615,1,Central,135,2,814,CHILD PORNOGRAPHY,...,CC,UNK,814.00,NaN,NaN,NaN,300 S MAIN ST,NaN,34.05,-118.25
607105,220126119,12/10/2022 0:00,12/10/2022 0:00,1515,1,Central,119,1,350,"THEFT, PERSON",...,CC,UNK,350.00,NaN,NaN,NaN,800 N ALAMEDA ST,NaN,34.06,-118.24
725418,231311708,6/2/2023 0:00,6/2/2023 0:00,1340,13,Newton,1341,1,440,THEFT PLAIN - PETTY ($950 & UNDER),...,CC,UNK,440.00,624.00,NaN,NaN,36TH ST,MAIN ST,34.02,-118.27
817845,230708724,4/22/2023 0:00,4/21/2023 0:00,1200,7,Wilshire,787,1,510,VEHICLE - STOLEN,...,CC,UNK,510.00,NaN,NaN,NaN,2200 WELLINGTON RD,NaN,34.04,-118.34
849894,230915357,10/16/2023 0:00,10/11/2023 0:00,1800,9,Van Nuys,946,2,664,"BUNCO, PETTY THEFT",...,CC,UNK,664.00,NaN,NaN,NaN,13800 OXNARD ST,NaN,34.18,-118.43
882208,241810568,6/8/2024 0:00,5/24/2024 0:00,1900,18,Southeast,1871,1,510,VEHICLE - STOLEN,...,NaN,UNK,510.00,NaN,NaN,NaN,13500 S FIGUEROA ST,NaN,33.91,-118.28
934059,240206384,1/24/2024 0:00,1/23/2024 0:00,2100,2,Rampart,249,1,330,BURGLARY FROM VEHICLE,...,CC,UNK,330.00,NaN,NaN,NaN,600 LUCAS AV,NaN,34.05,-118.26

In [23]:
crime[crime["LOCATION"].isin(missing_values)]

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
166567,201600732,7/25/2020 0:00,7/25/2020 0:00,400,16,Foothill,1677,1,121,"RAPE, FORCIBLE",...,IC,Invest Cont,121.00,NaN,NaN,NaN,UNK,LOCATION,34.22,-118.35

## Data Cleaning

In [24]:
columns_to_drop = [
    "Rpt Dist No",
    "Part 1-2",
    "Mocodes",
    "Premis Cd",
    "Premis Desc",
    "Weapon Used Cd",
    "Weapon Desc",
    "Status",
    "Status Desc",
    "Crm Cd 1",
    "Crm Cd 2",
    "Crm Cd 3",
    "Crm Cd 4",
    "LOCATION",
    "Cross Street"
]

crime = crime.drop(columns=columns_to_drop)

In [25]:
crime.columns

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Crm Cd', 'Crm Cd Desc', 'Vict Age', 'Vict Sex', 'Vict Descent', 'LAT',
       'LON'],
      dtype='str')

In [26]:
crime["Date Rptd"] = pd.to_datetime(crime["Date Rptd"])
crime["DATE OCC"] = pd.to_datetime(crime["DATE OCC"])
crime["TIME OCC"] = (
    crime["TIME OCC"]
    .astype(str)
    .str.zfill(4)
)

crime["TIME OCC"] = pd.to_datetime(crime["TIME OCC"], format="%H%M").dt.hour

In [27]:
crime.dtypes

DR_NO                    int64
Date Rptd       datetime64[us]
DATE OCC        datetime64[us]
TIME OCC                 int32
AREA                     int64
AREA NAME                  str
Crm Cd                   int64
Crm Cd Desc                str
Vict Age                 int64
Vict Sex                   str
Vict Descent               str
LAT                    float64
LON                    float64
dtype: object

In [28]:
crime.replace("-", np.nan, inplace=True)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Crm Cd,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,LAT,LON
0,190326475,2020-03-01,2020-03-01,21,7,Wilshire,510,VEHICLE - STOLEN,0,M,O,34.04,-118.35
1,200106753,2020-02-09,2020-02-08,18,1,Central,330,BURGLARY FROM VEHICLE,47,M,O,34.04,-118.26
2,200320258,2020-11-11,2020-11-04,17,3,Southwest,480,BIKE - STOLEN,19,X,X,34.02,-118.30
3,200907217,2023-05-10,2020-03-10,20,9,Van Nuys,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),19,M,O,34.16,-118.44
4,200412582,2020-09-09,2020-09-09,6,4,Hollenbeck,510,VEHICLE - STOLEN,0,NaN,NaN,34.08,-118.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005193,250304214,2025-02-23,2025-02-21,15,3,Southwest,510,VEHICLE - STOLEN,0,NaN,NaN,34.02,-118.29
1005194,250304203,2025-02-20,2025-02-13,21,3,Southwest,522,"VEHICLE, STOLEN - OTHER (MOTORIZED SCOOTERS, B...",0,NaN,NaN,34.03,-118.29
1005195,250504051,2025-01-14,2025-01-14,12,5,Harbor,210,ROBBERY,15,F,H,33.80,-118.31
1005196,251604136,2025-02-27,2025-02-27,15,16,Foothill,510,VEHICLE - STOLEN,0,NaN,NaN,34.24,-118.39
1005197,251904210,2025-03-25,2025-03-25,12,19,Mission,850,INDECENT EXPOSURE,35,F,H,34.27,-118.44

In [29]:
crime[crime["Vict Descent"].isin(missing_values)]

Empty DataFrame
Columns: [DR_NO, Date Rptd, DATE OCC, TIME OCC, AREA, AREA NAME, Crm Cd, Crm Cd Desc, Vict Age, Vict Sex, Vict Descent, LAT, LON]
Index: []

In [30]:
crime[crime["Vict Sex"].isin(missing_values)]

Empty DataFrame
Columns: [DR_NO, Date Rptd, DATE OCC, TIME OCC, AREA, AREA NAME, Crm Cd, Crm Cd Desc, Vict Age, Vict Sex, Vict Descent, LAT, LON]
Index: []

In [31]:
crime["Vict Sex"] = crime["Vict Sex"].replace("H", np.nan)

In [32]:
crime["Vict Sex"] = crime["Vict Sex"].replace("X", np.nan)

In [33]:
crime["Vict Sex"].value_counts(dropna=False)

Vict Sex
M      403916
F      358599
NaN    242683
Name: count, dtype: int64

In [34]:
crime["Vict Age"] = crime["Vict Age"].replace(0, np.nan)

In [35]:
crime["Vict Age"] = crime["Vict Age"].where(crime["Vict Age"] > 0, np.nan)

In [36]:
crime[crime["Vict Age"] <= 0]["Vict Age"].value_counts()

Series([], Name: count, dtype: int64)

In [37]:
crime["LAT"] = crime["LAT"].replace(0, np.nan)

In [38]:
crime["LON"] = crime["LON"].replace(0, np.nan)

In [39]:
crime[(crime["LAT"] == 0) & (crime["LON"] == 0)].shape[0]

0

## Data Analysis

### How has reported crime changed over time?

In [55]:
crime_2020_2023 = crime[crime["DATE OCC"].dt.year.between(2020, 2023)]
crime_2020_2023["Year"] = crime_2020_2023["DATE OCC"].dt.year
crime_2020_2023["Month"] = crime_2020_2023["DATE OCC"].dt.month

monthly_crimes = crime_2020_2023.groupby([
    crime_2020_2023["DATE OCC"].dt.year,
    crime_2020_2023["DATE OCC"].dt.month
]).size()

monthly_crimes = (
    crime_2020_2023
    .groupby(["Year", "Month"])
    .size()
    .reset_index(name="Crime Count")
)

monthly_crimes

    Year  Month  Crime Count
0   2020      1        18576
1   2020      2        17284
2   2020      3        16188
3   2020      4        15706
4   2020      5        17230
5   2020      6        17060
6   2020      7        17158
7   2020      8        16902
8   2020      9        15658
9   2020     10        16510
10  2020     11        15596
11  2020     12        15979
12  2021      1        16636
13  2021      2        15440
14  2021      3        16354
15  2021      4        16091
16  2021      5        17020
17  2021      6        17182
18  2021      7        18690
19  2021      8        18398
20  2021      9        18386
21  2021     10        19342
22  2021     11        18374
23  2021     12        17962
24  2022      1        18567
25  2022      2        17750
26  2022      3        19745
27  2022      4        19837
28  2022      5        20467
29  2022      6        20273
30  2022      7        20009
31  2022      8        20144
32  2022      9        19341
33  2022     10        20335
34  2022     11        18754
35  2022     12        20036
36  2023      1        19972
37  2023      2        18489
38  2023      3        19214
39  2023      4        18937
40  2023      5        18910
41  2023      6        18743
42  2023      7        19934
43  2023      8        20082
44  2023      9        19321
45  2023     10        20123
46  2023     11        19074
47  2023     12        19551

In [56]:
monthly_crimes = monthly_crimes.pivot(
    index="Month",
    columns="Year",
    values="Crime Count"
)

monthly_crimes

Year    2020   2021   2022   2023
Month
1      18576  16636  18567  19972
2      17284  15440  17750  18489
3      16188  16354  19745  19214
4      15706  16091  19837  18937
5      17230  17020  20467  18910
6      17060  17182  20273  18743
7      17158  18690  20009  19934
8      16902  18398  20144  20082
9      15658  18386  19341  19321
10     16510  19342  20335  20123
11     15596  18374  18754  19074
12     15979  17962  20036  19551

### What are the most commonly reported crime types?

In [40]:
top_10_crimes = crime["Crm Cd Desc"].value_counts().head(10)
top_10_crimes

Crm Cd Desc
VEHICLE - STOLEN                                           115247
BATTERY - SIMPLE ASSAULT                                    74847
BURGLARY FROM VEHICLE                                       63518
THEFT OF IDENTITY                                           62539
VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)     61094
BURGLARY                                                    57879
THEFT PLAIN - PETTY ($950 & UNDER)                          53723
ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT              53532
INTIMATE PARTNER - SIMPLE ASSAULT                           46712
THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)             41316
Name: count, dtype: int64

### Which areas report the most crime?

In [41]:
top_10_areas = crime["AREA NAME"].value_counts().head(10)
top_10_areas

AREA NAME
Central        69674
77th Street    61763
Pacific        59520
Southwest      57511
Hollywood      52430
N Hollywood    51107
Olympic        50071
Southeast      49941
Newton         49181
Wilshire       48240
Name: count, dtype: int64

### At what times of day is crime most frequently reported as occurring?

In [58]:
crime["TIME OCC"].value_counts().sort_index()

TIME OCC
0     40481
1     29764
2     25217
3     22193
4     18758
5     17292
6     23187
7     26270
8     37257
9     36534
10    43029
11    43670
12    67836
13    45593
14    49324
15    52839
16    52987
17    58827
18    59966
19    55616
20    56358
21    50800
22    49117
23    42283
Name: count, dtype: int64

In [43]:
crime["TIME OCC"].value_counts().sort_values(ascending=False).head(5)

TIME OCC
12    67836
18    59966
17    58827
20    56358
19    55616
Name: count, dtype: int64

### Victim Demographics

In [45]:
crime["Vict Sex"].value_counts(dropna=False)

Vict Sex
M      403916
F      358599
NaN    242683
Name: count, dtype: int64

In [46]:
crime["Vict Age"].value_counts().head(10)

Vict Age
30.00    22289
35.00    21836
31.00    21420
29.00    21345
28.00    20969
32.00    20845
33.00    20362
27.00    20131
34.00    19420
26.00    19326
Name: count, dtype: int64

In [44]:
crime["Vict Descent"].value_counts().head(10)

Vict Descent
H    296437
W    201451
B    135823
X    106699
O     78010
A     21340
K      5991
F      4838
C      4631
J      1586
Name: count, dtype: int64